management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      base-path: /

server:
  servlet:
    context-path: /whenyou-mdms-services
  port: 8084


spring:
  datasource:

    driverClassName: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/master-data

    username: postgres

    password: postgres

  liquibase:

    enabled: 'true'

    drop-first: 'false'

    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:

    hibernate:

      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    jwt:
      secret: IwXWuCZRv/a7SXuV/GIZvO/zELE00N5jYoXXoF3Y4ZPl+A62V4nwthL13vCzQiJ17DzWYkroiAonYbRX9fHHwA==
      expiration: 86400000
      header: Authorization
      prefix: Bearer
sms:
  api:
    url: https://thesmsbuddy.com/api/v1/sms/send

login-service:
  url: http://whenyou-vendor-onboarding-services





