management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      base-path: /

server:
  servlet:
    context-path: /pgr-services
  port: 8080

app:
  timezone: UTC

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    properties:
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
  kafka:
    #bootstrap-servers: b-1.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094,b-2.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094,b-3.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pgr-service
    security:
      protocol: SSL
  security:
      jwt:
        secret: ${JWT_SECRET}

services:
  mdms:
    tenant:
      id: kl
    url: ${MDMS_SERVICE_HOST}

  idgen:
    tenant:
      id: kl
    url: ${IDGEN_SERVICE_HOST}

  file:
    tenant:
      id: kl
    url: ${FILE_SERVICE_HOST}
  dmdm:
    tenant:
      id: kl
    url: ${DMDM_SERVICE_HOST}

  pdf:
    url: ${PDF_SERVICE_HOST}

  sms:
    url: ${SMS_SERVICE_HOST}

  otp:
    url: ${OTP_SERVICE_HOST}

  urlshortening:
    url: ${URLSHORTENING_SERVICE_HOST}




feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

aws:
  service-bucket: ${SERVICE_BUCKET}
  feedback-bucket: ${FEEDBACK_BUCKET}
  rptBucket : ${REPORT_BUCKET}
  dataBucket: ${DATA_BUCKET}
  service-role: ${SERVICE_ROLE}
  region: ${AWS_REGION}

ksm:
  kafka:
    topic:
      create-file : ${CREATE_TOPIC}
      update-file : ${UPDATE_TOPIC}
      resubmit-file: ${RESUBMIT_TOPIC}
cdn:
  lb:
    url: ${CDN_URL}

petition:
  lb:
    url: ${MASS_URL}

delete:
 lb:
  url: ${DELETE_URL}

edit:
  lb:
   url: ${EDIT_URL}

whatsapp:
  lb:
   url: ${DECLARATION_URL}

domain:
  url: ${DOMAIN_URL}



