--CREATE TABLE bank_details (
--    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--    general_info_id UUID NOT NULL,
--    beneficiary_name VARCHAR(255) NOT NULL,
--    account_number VARCHAR(50) NOT NULL,
--    confirm_account_number VARCHAR(50) NOT NULL,
--    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('SAVINGS', 'CURRENT', 'NRI_ACCOUNT')),
--    ifsc_code VARCHAR(11) NOT NULL,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    modified_date TIMESTAMP,
--    created_by UUID,
--    modified_by UUID,
--    CONSTRAINT fk_bank_details_general_info
--        FOREIGN KEY (general_info_id) REFERENCES general_information(id)
--        ON DELETE CASCADE
--);