--CREATE TABLE general_information (
--    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--    organization_name VARCHAR(150) NOT NULL,
--    organization_pan_no VARCHAR(20) NOT NULL,
--    organization_address TEXT NOT NULL,
--    itr BOOLEAN DEFAULT FALSE,
--    has_gstin BOOLEAN DEFAULT FALSE,
--    gst_no VARCHAR(50),
--    name VARCHAR(150),
--    email VARCHAR(150),
--    contact_number VARCHAR(20),
--    id_number VARCHAR(50),
--    declaration BOOLEAN DEFAULT FALSE,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    created_by UUID,
--    modified_by UUID,
--    modified_date TIMESTAMP
--);